### ISSUE TITLE
Create a Web flow

### ISSUE THREAD

**Issue by mitro-ubaidillah** [kelompok-2-immarsive/FE_Dashboard#2]
Create a web flow in Wimshical or Figma

![Image](https://user-images.githubusercontent.com/79407223/205419847-a3cef47f-66db-4c6d-9c6c-5c825c781950.png)
![Image](https://user-images.githubusercontent.com/79407223/205419846-3a314839-d430-4675-ad23-facab24adab6.png)

**Comment by mitro-ubaidillah** [comment]
masih ada kah yang perlu di revisi lagi ?

**Comment by Novalia9517** [comment]
udah kayanya kak mitro...

**Comment by mitro-ubaidillah** [comment]
okee ku close issue nya
