### ISSUE TITLE
Create Add Mentee page with Figma

### ISSUE THREAD

**Issue by Novalia9517** [kelompok-2-immarsive/FE_Dashboard#6]

**Comment by mitro-ubaidillah** [comment]
sementara sudah oke, perubahan untuk lebih baik langsung di codingan aja

**Comment by mitro-ubaidillah** [comment]
![Image](https://user-images.githubusercontent.com/79407223/205643082-39f58e58-3268-4ca8-9166-72931a6713d2.png)
